name: Build Windows Electron App

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: windows-latest # Specifies the Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npx electron-builder --win

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: windows-build
          path: dist/*.exe # Upload the .exe from the dist folder.